---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocdui
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cd.larsnieuwenhuizen.nl`)
      kind: Rule
      middlewares:
        - name: redirect-to-https
          namespace: default
      services:
        - name: argocd-server
          namespace: argocd
          port: 443
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocdui-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cd.larsnieuwenhuizen.nl`)
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 443
  tls:
    certResolver: le
