---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bjd
spec:
  destination:
    namespace: bjd
    server: https://kubernetes.default.svc
  project: bjd
  source:
    path: Deployment/digitalocean/acc
    repoURL: git@github.com:LarsNieuwenhuizen/bjd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
