apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
spec:
  destination:
    namespace: ghost
    server: https://kubernetes.default.svc
  project: default
  source:
    path: digitalocean
    repoURL: https://github.com/LarsNieuwenhuizen/ghost.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
