---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub
spec:
  destination:
    namespace: jetbrains
    server: https://kubernetes.default.svc
  project: default
  source:
    path: JetbrainsHub/digitalocean
    repoURL: git@github.com:LarsNieuwenhuizen/Cluster-persistence-applications.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
