apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-nginx
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/nginx
    repoURL: https://github.com/LarsNieuwenhuizen/argocd-test.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
