---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sparkell-prod
spec:
  destination:
    namespace: sparkell-prod
    server: https://kubernetes.default.svc
  project: sparkell
  source:
    path: Deployment/digitalocean/prod
    repoURL: git@github.com:LarsNieuwenhuizen/SparKell.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: sparkell-acc
#spec:
#  destination:
#    namespace: sparkell-acc
#    server: https://kubernetes.default.svc
#  project: sparkell
#  source:
#    path: Deployment/digitalocean/acc
#    repoURL: git@github.com:LarsNieuwenhuizen/SparKell.git
#    targetRevision: master
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
